#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v27
# autospec commit: 65cf152
#
Name     : bubblewrap
Version  : 0.11.0
Release  : 13
URL      : https://github.com/projectatomic/bubblewrap/archive/v0.11.0/bubblewrap-0.11.0.tar.gz
Source0  : https://github.com/projectatomic/bubblewrap/archive/v0.11.0/bubblewrap-0.11.0.tar.gz
Summary  : Core execution tool for unprivileged containers
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.0+
Requires: bubblewrap-bin = %{version}-%{release}
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}
Requires: bubblewrap-man = %{version}-%{release}
BuildRequires : bash-completion-dev
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : libcap-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(libcap)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Bubblewrap (/usr/bin/bwrap) is a core execution engine for unprivileged
containers that works as a setuid binary on kernels without
user namespaces.

%package bin
Summary: bin components for the bubblewrap package.
Group: Binaries
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}

%description bin
bin components for the bubblewrap package.


%package data
Summary: data components for the bubblewrap package.
Group: Data

%description data
data components for the bubblewrap package.


%package license
Summary: license components for the bubblewrap package.
Group: Default

%description license
license components for the bubblewrap package.


%package man
Summary: man components for the bubblewrap package.
Group: Default

%description man
man components for the bubblewrap package.


%prep
%setup -q -n bubblewrap-0.11.0
cd %{_builddir}/bubblewrap-0.11.0
pushd ..
cp -a bubblewrap-0.11.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748631830
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/bubblewrap
cp %{_builddir}/bubblewrap-%{version}/COPYING %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/bubblewrap-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/bwrap
/usr/bin/bwrap

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/bwrap
/usr/share/zsh/site-functions/_bwrap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bwrap.1
