#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bubblewrap
Version  : 0.6.2
Release  : 10
URL      : https://github.com/projectatomic/bubblewrap/archive/v0.6.2/bubblewrap-0.6.2.tar.gz
Source0  : https://github.com/projectatomic/bubblewrap/archive/v0.6.2/bubblewrap-0.6.2.tar.gz
Summary  : Core execution tool for unprivileged containers
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.0+
Requires: bubblewrap-bin = %{version}-%{release}
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}
Requires: bubblewrap-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : libcap-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(libcap)

%description
Bubblewrap (/usr/bin/bwrap) is a core execution engine for unprivileged
containers that works as a setuid binary on kernels without
user namespaces.

%package bin
Summary: bin components for the bubblewrap package.
Group: Binaries
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}

%description bin
bin components for the bubblewrap package.


%package data
Summary: data components for the bubblewrap package.
Group: Data

%description data
data components for the bubblewrap package.


%package license
Summary: license components for the bubblewrap package.
Group: Default

%description license
license components for the bubblewrap package.


%package man
Summary: man components for the bubblewrap package.
Group: Default

%description man
man components for the bubblewrap package.


%prep
%setup -q -n bubblewrap-0.6.2
cd %{_builddir}/bubblewrap-0.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664889436
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/bubblewrap
cp %{_builddir}/bubblewrap-%{version}/COPYING %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/bubblewrap-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bwrap

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/bwrap
/usr/share/zsh/site-functions/_bwrap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bwrap.1
