#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bubblewrap
Version  : 0.3.3
Release  : 6
URL      : https://github.com/projectatomic/bubblewrap/archive/v0.3.3/bubblewrap-0.3.3.tar.gz
Source0  : https://github.com/projectatomic/bubblewrap/archive/v0.3.3/bubblewrap-0.3.3.tar.gz
Summary  : Core execution tool for unprivileged containers
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1+
Requires: bubblewrap-bin = %{version}-%{release}
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}
Requires: bubblewrap-man = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : libcap-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(bash-completion)

%description
Bubblewrap (/usr/bin/bwrap) is a core execution engine for unprivileged
containers that works as a setuid binary on kernels without
user namespaces.

%package bin
Summary: bin components for the bubblewrap package.
Group: Binaries
Requires: bubblewrap-data = %{version}-%{release}
Requires: bubblewrap-license = %{version}-%{release}

%description bin
bin components for the bubblewrap package.


%package data
Summary: data components for the bubblewrap package.
Group: Data

%description data
data components for the bubblewrap package.


%package license
Summary: license components for the bubblewrap package.
Group: Default

%description license
license components for the bubblewrap package.


%package man
Summary: man components for the bubblewrap package.
Group: Default

%description man
man components for the bubblewrap package.


%prep
%setup -q -n bubblewrap-0.3.3
cd %{_builddir}/bubblewrap-0.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576864798
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1576864798
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bubblewrap
cp %{_builddir}/bubblewrap-0.3.3/COPYING %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1
cp %{_builddir}/bubblewrap-0.3.3/LICENSE %{buildroot}/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bwrap

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/bwrap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bubblewrap/ba8966e2473a9969bdcab3dc82274c817cfd98a1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bwrap.1
